title: Clever Name
email: jonnie@cleverna.me
description: Clever Name
baseurl: ""
url: "https://cleverna.me"
github_username: JonnieCache
excerpt_separator: <!-- more -->

# Build settings
markdown: kramdown
remote_theme: yous/whiteglass
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
